name: ramp-healthcare-fees
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - scikit-learn>=0.22
  - joblib
  - cloudpickle
  - pandas
  - matplotlib
  - pip:
    - ramp-workflow
    - holidays
    - geopy
